GameCave/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameCave.Data;
using Microsoft.AspNetCore.Authorization;
using GameCave.Services;

namespace GameCave.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICompanyService _companyService;

        public CompaniesController(ApplicationDbContext context, ICompanyService companyService)
        {
            _context = context;
            _companyService = companyService;
        }

        // GET: Companies
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var items = _companyService.GetAllCompaniesAsync();
            return View(await items);
        }

        // GET: Companies/Details/5
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var company = await _companyService.GetCompanyByIdAsync(id.Value);

            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name,Id")] Company company)
        {
            if (ModelState.IsValid)
            {
                await _companyService.CreateAsync(company);
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var company = await _companyService.GetCompanyByIdAsync(id.Value);

            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _companyService.UpdateAsync(company);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Company == null)
            {
                return NotFound();
            }

            var company = await _companyService.GetCompanyByIdAsync(id.Value);

            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Company == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Company'  is null.");
            }

            await _companyService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        // check if company already exists
        private bool CompanyExists(int id)
        {
            return (_context.Company?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GameCave/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameCave.Data;
using Microsoft.AspNetCore.Authorization;
using GameCave.Services;
using Microsoft.AspNetCore.Identity;

namespace GameCave.Controllers
{
    public class GenresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IGenreService _genreService;
        private readonly UserManager<IdentityUser> _userManager;
        public GenresController(ApplicationDbContext context, IGenreService genreService, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _genreService = genreService;
        }

        // GET: Genres
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var item = _genreService.GetAllGenresAsync();
            return View(await item);
        }

        // GET: Genres/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _genreService.GetGenreByIdAsync(id.Value);

            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                string userId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
                await _genreService.CreateAsync(genre, userId);
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _genreService.GetGenreByIdAsync(id.Value);

            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string userId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
                    await _genreService.UpdateAsync(genre, userId);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _genreService.GetGenreByIdAsync(id.Value);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genre == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Genre'  is null.");
            }

            await _genreService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
            return (_context.Genre?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GameCave/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameCave.Data;
using GameCave.Models.ViewModels.ReviewVMs;
using Microsoft.AspNetCore.Identity;
using GameCave.Services;
using Microsoft.AspNetCore.Authorization;

namespace GameCave.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private IReviewService _reviewService;

        public ReviewsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IReviewService reviewService)
        {
            _context = context;
            _userManager = userManager;
            _reviewService = reviewService;
        }

        // GET: Reviews
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var items = _reviewService.GetAllReviewsAsync();
            return View(await items);
        }

        // GET: Reviews/Details/5

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            return View(await _reviewService.GetReviewByIdAsync(id.Value));
        }

        // GET: Reviews/Create

        [Authorize]
        public IActionResult Create(int gameId)
        {
            ViewData["gameId"] = gameId;
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ReviewViewModel reviewView)
        {
            if (ModelState.IsValid)
            {
                string userId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
                await _reviewService.CreateAsync(reviewView, userId);
                return RedirectToAction("Details", "Games", new { id = reviewView.GameID });
            }
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            return View(reviewView);
        }

        // GET: Reviews/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _reviewService.GetReviewByIdAsync(id.Value);

            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [FromForm] ReviewViewModel reviewView)
        {
            if (id != reviewView.Id)
            {
                return NotFound();
            }

#pragma warning disable CS8602 // Dereference of a possibly null reference.
            reviewView.GameID = (await _context.Review.FindAsync(id)).GameID;


            if (ModelState.IsValid)
            {
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
                Review review = await _context.Review.FindAsync(id);
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
                review.Title = reviewView.Title;
                review.Description = reviewView.Description;
                review.GameID = reviewView.GameID;
                review.Modified = DateTime.Now;
                review.ModifiedById = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
                review.ModifiedBy = await _userManager.FindByNameAsync(User.Identity.Name);

                _context.Update(review);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "Games", new { id = reviewView.GameID });
            }
#pragma warning restore CS8602 // Dereference of a possibly null reference.
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            ViewData["CreatedById"] = new SelectList(_context.Users, "Id", "Id", reviewView.CreatedById);
            ViewData["GameID"] = new SelectList(_context.Game, "Id", "Id", reviewView.GameID);
            ViewData["ModifiedById"] = new SelectList(_context.Users, "Id", "Id", reviewView.ModifiedById);

            return View(reviewView);
        }

        // GET: Reviews/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _reviewService.GetReviewByIdAsync(id.Value);

            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Review == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Review'  is null.");
            }

            int gameId = (await _reviewService.GetReviewByIdAsync(id)).GameID;
            await _reviewService.DeleteAsync(id);

            return RedirectToAction("Details", "Games", new { id = gameId });
        }
    }
}

GameCave/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameCave</title>@*
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    @*<link rel="stylesheet" href="~/GameCave.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <div class="header">
            <nav>
                <div class="left">
                    @using Microsoft.AspNetCore.Identity
                    @inject UserManager<IdentityUser> UserManager

                    <a asp-area="" asp-controller="Games" asp-action="Index"><img src="~/image/webpage_imgs/logo.png" id="logo" alt=""></a>
                    <a class="bttn-page" asp-area="" asp-controller="Games" asp-action="Index">Home</a>

                    @if (User.Identity.Name != null)
                    {
                        @if (UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), "admin").Result)
                        {
                            <a class="bttn-page" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                            <a class="bttn-page" asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a>
                            <a class="bttn-page" asp-area="" asp-controller="Companies" asp-action="Index">Companies</a>
                        }

                    }
                </div>

                <div class="right">
                    <a class="bttn-page" asp-area="" asp-controller="Carts" asp-action="Index" title="Your cart">
                        <i class="bi bi-cart-fill"></i>
                    </a>
                    @using Microsoft.AspNetCore.Identity
                    @inject SignInManager<IdentityUser> SignInManager
                    @inject UserManager<IdentityUser> UserManager
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a class="bttn-page" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage Account">
                            <i class="bi bi-person-fill"></i>
                        </a>

                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class="bttn-page" title="Log out">
                                <i class="bi bi-box-arrow-right"></i>
                            </button>
                        </form>
                    }
                    else
                    {
                        <a class="bttn-page" asp-area="Identity" asp-page="/Account/Login">
                            <i class="bi bi-person-fill"></i>
                        </a>
                    }
                </div>
            </nav>
        </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <hr />

    <footer>
        <div class="container">
            <a asp-area="" asp-controller="Games" asp-action="Index"><img src="~/image/webpage_imgs/logo.png" id="logo" alt=""></a>
            <a class="link-button" asp-area="" asp-controller="Games" asp-action="Index">Home</a>

            @if (User.Identity.IsAuthenticated && UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), "admin").Result)
            {
                <a class="link-button" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                <a class="link-button" asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a>
                <a class="link-button" asp-area="" asp-controller="Companies" asp-action="Index">Companies</a>
            }

            <a class="link-button" asp-area="" asp-controller="Carts" asp-action="Index">My Cart</a>
            <a class="link-button" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage Account">My Profile</a>
        </div>
        <p>All rights reserved. 2023</p>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>